# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via \{\{ site.title \}\}, \{\{ site.github_repo \}\}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via \{\{ site.myvariable \}\}.
title: "Stat 33a: Introduction to Programming in R"
tagline: Course Overview
description: "An introduction to the R statistical software for students with minimal prior experience with programming. This course prepares students for data analysis with R. The focus is on the computational model that underlies the R language with the goal of providing a foundation for coding. Topics include data types and structures, such as vectors, data frames and lists; the REPL evaluation model; function calls, argument matching, and environments; writing simple functions and control flow. Tools for reading, analyzing, and plotting data are covered, such as data input/output, reshaping data, the formula language, and graphics models.
"
author: "SCF"
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://stat33a.berkeley.edu'
exclude: ["Gemfile", "Gemfile.lock", "LICENSE"]
logo: 'resources/logo.png'

ga_tracking: "G-"

# Theme settings
remote_theme: just-the-docs/just-the-docs@v0.7.0
color_scheme: light
search_enabled: true
heading_anchors: true
permalink: pretty

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false